--liquibase formatted sql

--changeset goianao:001
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'administrador' AND LOWER(table_schema) = 'public'
-- Feature 001 (identidade/papeis) e 002 (edicoes).
-- SQL deliberadamente portavel: roda em PostgreSQL e em H2 (modo PostgreSQL),
-- para que dev/test funcionem sem depender de um servidor de banco instalado.

CREATE TABLE administrador (
    cpf        VARCHAR(11)  NOT NULL,
    nome       VARCHAR(200) NOT NULL,
    criado_em  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_administrador PRIMARY KEY (cpf)
);

CREATE TABLE edicao (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ano           INTEGER      NOT NULL,
    descricao     VARCHAR(500),
    status        VARCHAR(20)  NOT NULL,
    vigente       BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 'S' quando vigente, NULL caso contrario. Como NULLs sao distintos em um
    -- indice unico (PostgreSQL e H2), isto materializa no banco a invariante
    -- "no maximo uma edicao vigente" (002/RF-5) sem indice parcial.
    vigente_unico VARCHAR(1),
    criado_em     TIMESTAMP    NOT NULL,
    atualizado_em TIMESTAMP,
    CONSTRAINT pk_edicao          PRIMARY KEY (id),
    CONSTRAINT uk_edicao_ano      UNIQUE (ano),
    CONSTRAINT uk_edicao_vigente  UNIQUE (vigente_unico),
    CONSTRAINT ck_edicao_status   CHECK (status IN ('RASCUNHO', 'PUBLICADA'))
);
