--liquibase formatted sql

--changeset goianao:002
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'unidade_judiciaria' AND LOWER(table_schema) = 'public'
-- Feature 004: unidades judiciarias (espelho do EGESP), magistrados
-- reconhecidos por edicao e seus reconhecimentos (unidade + selo).

CREATE TABLE unidade_judiciaria (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    -- nome exatamente como veio do EGESP (impresso no certificado)
    nome           VARCHAR(300) NOT NULL,
    -- forma canonica (trim + minuscula + sem acentos) usada para casar a
    -- unidade entre as duas integracoes; e ela que carrega a unicidade
    nome_canonico  VARCHAR(300) NOT NULL,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_unidade            PRIMARY KEY (id),
    CONSTRAINT uk_unidade_canonico   UNIQUE (nome_canonico)
);

CREATE TABLE magistrado_reconhecido (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id     BIGINT       NOT NULL,
    cpf           VARCHAR(11)  NOT NULL,
    nome          VARCHAR(200) NOT NULL,
    criado_em     TIMESTAMP    NOT NULL,
    atualizado_em TIMESTAMP,
    CONSTRAINT pk_magistrado          PRIMARY KEY (id),
    CONSTRAINT uk_magistrado_edicao_cpf UNIQUE (edicao_id, cpf),
    CONSTRAINT fk_magistrado_edicao   FOREIGN KEY (edicao_id) REFERENCES edicao (id)
);

CREATE INDEX ix_magistrado_cpf ON magistrado_reconhecido (cpf);

CREATE TABLE reconhecimento (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    magistrado_id BIGINT      NOT NULL,
    unidade_id    BIGINT      NOT NULL,
    selo          VARCHAR(20) NOT NULL,
    criado_em     TIMESTAMP   NOT NULL,
    CONSTRAINT pk_reconhecimento          PRIMARY KEY (id),
    CONSTRAINT uk_reconhecimento_unidade  UNIQUE (magistrado_id, unidade_id),
    CONSTRAINT fk_reconhecimento_magistrado FOREIGN KEY (magistrado_id) REFERENCES magistrado_reconhecido (id),
    CONSTRAINT fk_reconhecimento_unidade    FOREIGN KEY (unidade_id)    REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_reconhecimento_selo      CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE'))
);
