--liquibase formatted sql

--changeset goianao:005
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'certificado_emitido' AND LOWER(table_schema) = 'public'
-- Features 005/006/007: registro de cada certificado logico emitido.
-- O PDF nao e armazenado (gerado sob demanda); guardam-se metadados e o
-- codigo de validacao, que e estavel entre reemissoes.

CREATE TABLE certificado_emitido (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id        BIGINT       NOT NULL,
    tipo             VARCHAR(20)  NOT NULL,
    cpf_emissor      VARCHAR(11)  NOT NULL,
    nome_emissor     VARCHAR(200) NOT NULL,
    unidade_id       BIGINT       NOT NULL,
    selo             VARCHAR(20)  NOT NULL,
    codigo_validacao VARCHAR(32)  NOT NULL,
    emitido_em       TIMESTAMP    NOT NULL,
    reemitido_em     TIMESTAMP,
    total_emissoes   INTEGER      NOT NULL DEFAULT 1,
    CONSTRAINT pk_certificado          PRIMARY KEY (id),
    CONSTRAINT uk_certificado_codigo   UNIQUE (codigo_validacao),
    CONSTRAINT uk_certificado_logico   UNIQUE (edicao_id, tipo, cpf_emissor, unidade_id),
    CONSTRAINT fk_certificado_edicao   FOREIGN KEY (edicao_id)  REFERENCES edicao (id),
    CONSTRAINT fk_certificado_unidade  FOREIGN KEY (unidade_id) REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_certificado_tipo     CHECK (tipo IN ('MAGISTRADO', 'SERVIDOR')),
    CONSTRAINT ck_certificado_selo     CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE'))
);

CREATE INDEX ix_certificado_emissor ON certificado_emitido (cpf_emissor, edicao_id);
