--liquibase formatted sql

--changeset goianao:007
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'usuario' AND LOWER(table_schema) = 'public'
-- Cadastro de usuarios do sistema.
--
-- Ate aqui a identidade vinha inteira do provedor (mockado) e o papel de
-- administrador era uma linha em `administrador`. Com o superadministrador,
-- passa a existir um cadastro proprio: quem entra, com que papel, lotado onde.
--
-- O CPF e obrigatorio e unico porque e a chave do dominio inteiro -- magistrado
-- reconhecido, servidor habilitado e certificado emitido sao todos indexados
-- por ele. Um usuario sem CPF conseguiria entrar e nao acharia nada seu.
--
-- A senha e opcional: hoje entra pelo login com e-mail, mas quando o SSO
-- assumir a autenticacao os usuarios existirao sem senha alguma.
CREATE TABLE usuario (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    cpf              VARCHAR(11)  NOT NULL,
    nome             VARCHAR(200) NOT NULL,
    email            VARCHAR(200) NOT NULL,
    senha_hash       VARCHAR(100),
    unidade_lotacao  VARCHAR(300),
    -- Area de atuacao do magistrado (Civel, Criminal, Familia...). Texto livre:
    -- a taxonomia do tribunal nao esta definida, e um enum errado aqui sairia
    -- mais caro de corrigir do que um texto.
    area_atuacao     VARCHAR(150),
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    CONSTRAINT pk_usuario        PRIMARY KEY (id),
    CONSTRAINT uk_usuario_cpf    UNIQUE (cpf),
    CONSTRAINT uk_usuario_email  UNIQUE (email)
);

-- Papeis acumulam (001/RF-3): a tabela e um conjunto, nao uma coluna.
CREATE TABLE usuario_papel (
    usuario_id  BIGINT      NOT NULL,
    papel       VARCHAR(20) NOT NULL,
    CONSTRAINT pk_usuario_papel PRIMARY KEY (usuario_id, papel),
    CONSTRAINT fk_usuario_papel_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT ck_usuario_papel CHECK (
        papel IN ('SUPERADMIN', 'ADMINISTRADOR', 'MAGISTRADO', 'SERVIDOR')
    )
);
