-- Feature 003: layout do certificado por edicao x selo x tipo.
-- As areas de texto sao guardadas como JSON em VARCHAR (portavel entre
-- PostgreSQL e H2) e convertidas na camada JPA.

CREATE TABLE layout_certificado (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    edicao_id      BIGINT        NOT NULL,
    selo           VARCHAR(20)   NOT NULL,
    tipo           VARCHAR(20)   NOT NULL,
    imagem_ref     VARCHAR(300)  NOT NULL,
    imagem_largura INTEGER       NOT NULL,
    imagem_altura  INTEGER       NOT NULL,
    area_nome      VARCHAR(2000) NOT NULL,
    area_unidade   VARCHAR(2000) NOT NULL,
    area_codigo    VARCHAR(2000) NOT NULL,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    CONSTRAINT pk_layout          PRIMARY KEY (id),
    CONSTRAINT uk_layout_combinacao UNIQUE (edicao_id, selo, tipo),
    CONSTRAINT fk_layout_edicao   FOREIGN KEY (edicao_id) REFERENCES edicao (id),
    CONSTRAINT ck_layout_selo     CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE')),
    CONSTRAINT ck_layout_tipo     CHECK (tipo IN ('MAGISTRADO', 'SERVIDOR'))
);
