--liquibase formatted sql

--changeset goianao:edicao-001
-- Esquema de UMA edicao do premio (feature 011).
--
-- Este arquivo nao roda no esquema compartilhado: ele e aplicado, uma vez por
-- edicao, dentro do schema dela -- `edicao_2026`, `edicao_2027` e assim por
-- diante --, por BaseDaEdicao. Cada schema tem o seu proprio
-- databasechangelog, entao uma edicao criada daqui a tres anos recebe o esquema
-- que estiver em vigor naquele momento, sem tocar nas anteriores.
--
-- O conteudo e o estado final das migracoes 001 a 011, consolidado: o mesmo
-- esquema que a base compartilhada tinha na vespera desta feature. Consolidar
-- em vez de repetir as onze migracoes e deliberado -- a base de uma edicao nova
-- nasce vazia, e nao ha historia para reproduzir.
--
-- AUSENCIA DE CHAVE ESTRANGEIRA PARA `edicao`. As colunas `edicao_id`
-- continuam aqui, preenchidas, porque e por elas que as consultas de cinco
-- features filtram -- e dentro do schema elas sempre casam. Mas a tabela
-- `edicao` mora no esquema compartilhado, e uma chave estrangeira entre
-- esquemas amarraria o nome do compartilhado dentro de cada schema de edicao.
-- O isolamento ja e dado pelo schema: e ele que garante que a linha e desta
-- edicao, nao a restricao.
--
-- SQL portavel entre PostgreSQL e H2 (modo PostgreSQL), como o restante do
-- projeto: os mesmos arquivos servem a producao, ao desenvolvimento e aos
-- testes.

-- Cadastro de quem entra no sistema nesta edicao. O e-mail e a chave (DI-24);
-- o CPF e opcional e apenas informativo.
CREATE TABLE usuario (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    cpf              VARCHAR(11),
    nome             VARCHAR(200) NOT NULL,
    email            VARCHAR(200) NOT NULL,
    senha_hash       VARCHAR(100),
    unidade_lotacao  VARCHAR(300),
    area_atuacao     VARCHAR(150),
    matricula        BIGINT,
    login_ad         VARCHAR(100),
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em        TIMESTAMP    NOT NULL,
    atualizado_em    TIMESTAMP,
    CONSTRAINT pk_usuario       PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

-- Papeis acumulam (001/RF-3): a tabela e um conjunto, nao uma coluna. Como o
-- cadastro e por edicao, tambem os papeis sao: a mesma pessoa pode ser
-- magistrada em um ano e apenas servidora em outro (011/RF-8).
CREATE TABLE usuario_papel (
    usuario_id  BIGINT      NOT NULL,
    papel       VARCHAR(20) NOT NULL,
    CONSTRAINT pk_usuario_papel         PRIMARY KEY (usuario_id, papel),
    CONSTRAINT fk_usuario_papel_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT ck_usuario_papel CHECK (
        papel IN ('SUPERADMIN', 'ADMINISTRADOR', 'MAGISTRADO', 'SERVIDOR')
    )
);

-- Origem dos administradores anteriores ao cadastro de usuarios, e da carga de
-- demonstracao.
CREATE TABLE administrador (
    email      VARCHAR(200) NOT NULL,
    cpf        VARCHAR(11),
    nome       VARCHAR(200) NOT NULL,
    criado_em  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_administrador PRIMARY KEY (email)
);

CREATE TABLE unidade_judiciaria (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    -- nome exatamente como veio do RH (impresso no certificado)
    nome           VARCHAR(300) NOT NULL,
    -- forma canonica (trim + minuscula + sem acentos), que carrega a unicidade
    nome_canonico  VARCHAR(300) NOT NULL,
    codigo_siedos  BIGINT,
    comarca        VARCHAR(150),
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    -- quem responde pela unidade nesta edicao (DI-23)
    responsavel_id BIGINT,
    criado_em      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_unidade              PRIMARY KEY (id),
    CONSTRAINT uk_unidade_canonico     UNIQUE (nome_canonico),
    CONSTRAINT uk_unidade_codigo_siedos UNIQUE (codigo_siedos),
    CONSTRAINT fk_unidade_responsavel  FOREIGN KEY (responsavel_id) REFERENCES usuario (id)
);

CREATE TABLE magistrado_reconhecido (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id     BIGINT       NOT NULL,
    email         VARCHAR(200) NOT NULL,
    cpf           VARCHAR(11),
    nome          VARCHAR(200) NOT NULL,
    criado_em     TIMESTAMP    NOT NULL,
    atualizado_em TIMESTAMP,
    CONSTRAINT pk_magistrado              PRIMARY KEY (id),
    CONSTRAINT uk_magistrado_edicao_email UNIQUE (edicao_id, email)
);

CREATE INDEX ix_magistrado_email ON magistrado_reconhecido (email);

CREATE TABLE reconhecimento (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    magistrado_id BIGINT      NOT NULL,
    unidade_id    BIGINT      NOT NULL,
    selo          VARCHAR(20) NOT NULL,
    criado_em     TIMESTAMP   NOT NULL,
    CONSTRAINT pk_reconhecimento            PRIMARY KEY (id),
    CONSTRAINT uk_reconhecimento_unidade    UNIQUE (magistrado_id, unidade_id),
    CONSTRAINT fk_reconhecimento_magistrado FOREIGN KEY (magistrado_id) REFERENCES magistrado_reconhecido (id),
    CONSTRAINT fk_reconhecimento_unidade    FOREIGN KEY (unidade_id)    REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_reconhecimento_selo       CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE'))
);

CREATE TABLE layout_certificado (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    edicao_id      BIGINT        NOT NULL,
    selo           VARCHAR(20)   NOT NULL,
    tipo           VARCHAR(20)   NOT NULL,
    imagem_ref     VARCHAR(300)  NOT NULL,
    imagem_largura INTEGER       NOT NULL,
    imagem_altura  INTEGER       NOT NULL,
    area_nome      VARCHAR(2000) NOT NULL,
    area_unidade   VARCHAR(2000) NOT NULL,
    area_codigo    VARCHAR(2000) NOT NULL,
    criado_em      TIMESTAMP     NOT NULL,
    atualizado_em  TIMESTAMP,
    CONSTRAINT pk_layout            PRIMARY KEY (id),
    CONSTRAINT uk_layout_combinacao UNIQUE (edicao_id, selo, tipo),
    CONSTRAINT ck_layout_selo       CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE')),
    CONSTRAINT ck_layout_tipo       CHECK (tipo IN ('MAGISTRADO', 'SERVIDOR'))
);

-- A arte fora do disco: o pod do OpenShift roda sem volume persistente, e uma
-- reemissao feita daqui a anos precisa sair identica a original.
CREATE TABLE arte_layout (
    referencia  VARCHAR(64)  NOT NULL,
    conteudo    BYTEA        NOT NULL,
    extensao    VARCHAR(10)  NOT NULL,
    tamanho     BIGINT       NOT NULL,
    criado_em   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_arte_layout PRIMARY KEY (referencia)
);

-- Quem pode emitir o certificado de servidor, por unidade. Remocao e logica
-- (ativo = false) para auditoria.
CREATE TABLE servidor_habilitado (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id      BIGINT       NOT NULL,
    unidade_id     BIGINT       NOT NULL,
    email          VARCHAR(200) NOT NULL,
    cpf            VARCHAR(11),
    matricula      BIGINT,
    nome           VARCHAR(200) NOT NULL,
    origem         VARCHAR(10)  NOT NULL,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_por     VARCHAR(200),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_por VARCHAR(200),
    atualizado_em  TIMESTAMP,
    CONSTRAINT pk_servidor_habilitado PRIMARY KEY (id),
    CONSTRAINT uk_servidor_habilitado UNIQUE (edicao_id, unidade_id, email),
    CONSTRAINT fk_servidor_unidade    FOREIGN KEY (unidade_id) REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_servidor_origem     CHECK (origem IN ('EGESP', 'MANUAL'))
);

CREATE INDEX ix_servidor_habilitado_email ON servidor_habilitado (email, edicao_id);

-- O PDF nao e armazenado (gerado sob demanda); guardam-se metadados e o codigo
-- de validacao, que e estavel entre reemissoes.
CREATE TABLE certificado_emitido (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id        BIGINT       NOT NULL,
    tipo             VARCHAR(20)  NOT NULL,
    email_emissor    VARCHAR(200) NOT NULL,
    cpf_emissor      VARCHAR(11),
    nome_emissor     VARCHAR(200) NOT NULL,
    unidade_id       BIGINT       NOT NULL,
    selo             VARCHAR(20)  NOT NULL,
    codigo_validacao VARCHAR(32)  NOT NULL,
    emitido_em       TIMESTAMP    NOT NULL,
    reemitido_em     TIMESTAMP,
    total_emissoes   INTEGER      NOT NULL DEFAULT 1,
    CONSTRAINT pk_certificado         PRIMARY KEY (id),
    CONSTRAINT uk_certificado_codigo  UNIQUE (codigo_validacao),
    CONSTRAINT uk_certificado_logico  UNIQUE (edicao_id, tipo, email_emissor, unidade_id),
    CONSTRAINT fk_certificado_unidade FOREIGN KEY (unidade_id) REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_certificado_tipo    CHECK (tipo IN ('MAGISTRADO', 'SERVIDOR')),
    CONSTRAINT ck_certificado_selo    CHECK (selo IN ('BRONZE', 'PRATA', 'OURO', 'DIAMANTE'))
);

CREATE INDEX ix_certificado_emissor ON certificado_emitido (email_emissor, edicao_id);
