--liquibase formatted sql

--changeset goianao:004
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = 'servidor_habilitado' AND LOWER(table_schema) = 'public'
-- Feature 008: snapshot, por edicao x unidade, de quem pode emitir o
-- certificado de servidor. Remocao e logica (ativo = false) para auditoria.

CREATE TABLE servidor_habilitado (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    edicao_id      BIGINT       NOT NULL,
    unidade_id     BIGINT       NOT NULL,
    cpf            VARCHAR(11)  NOT NULL,
    nome           VARCHAR(200) NOT NULL,
    origem         VARCHAR(10)  NOT NULL,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_por     VARCHAR(11),
    criado_em      TIMESTAMP    NOT NULL,
    atualizado_por VARCHAR(11),
    atualizado_em  TIMESTAMP,
    CONSTRAINT pk_servidor_habilitado    PRIMARY KEY (id),
    CONSTRAINT uk_servidor_habilitado    UNIQUE (edicao_id, unidade_id, cpf),
    CONSTRAINT fk_servidor_edicao        FOREIGN KEY (edicao_id)  REFERENCES edicao (id),
    CONSTRAINT fk_servidor_unidade       FOREIGN KEY (unidade_id) REFERENCES unidade_judiciaria (id),
    CONSTRAINT ck_servidor_origem        CHECK (origem IN ('EGESP', 'MANUAL'))
);

CREATE INDEX ix_servidor_habilitado_cpf ON servidor_habilitado (cpf, edicao_id);
